### ISSUE TITLE
Map Template plugins does not work with version 1.2.x of mapstore 

### ISSUE THREAD

**Issue by catmorales** [georchestra/mapstore2-georchestra#343]
**Instance :** https://portail-test.sig.rennesmetropole.fr
**Mapstore installation :** Docker image 1.2.x version  from https://hub.docker.com/r/geosolutionsit/mapstore2-georchestra/tags?page=1&ordering=last_updated
**Deployment date :** 22/02/2021 14h36
**Tested on :** https://portail-test.sig.rennesmetropole.fr/mapstore/#/context/testcat but it's the same problem on all contexts
**Issue :**
Impossible to add a new map template from the context manager .

![image](https://user-images.githubusercontent.com/4659829/111482657-6657a080-8734-11eb-8bd6-1d74484c1e4c.png)

**Comment by tdipisa** [comment]
@offtherailz Can you please check this? It is not happening in GeoSolutions DEV and QA instances. In portail-test instance I found this error in console:

```
geOrchestra.js?ddf76ae26212cae88b44:2 TypeError: t.title.toLowerCase is not a function
    at geOrchestra.js?ddf76ae26212cae88b44:2
    at Array.filter (<anonymous>)
    at filter (geOrchestra.js?ddf76ae26212cae88b44:2)
    at tt (geOrchestra.js?ddf76ae26212cae88b44:2)
    at nt (geOrchestra.js?ddf76ae26212cae88b44:2)
    at na (geOrchestra.js?ddf76ae26212cae88b44:2)
    at Fs (geOrchestra.js?ddf76ae26212cae88b44:2)
    at ol (geOrchestra.js?ddf76ae26212cae88b44:2)
    at nl (geOrchestra.js?ddf76ae26212cae88b44:2)
    at Zs (geOrchestra.js?ddf76ae26212cae88b44:2)
    at geOrchestra.js?ddf76ae26212cae88b44:2
    at t.unstable_runWithPriority (geOrchestra.js?ddf76ae26212cae88b44:2)
    at Bo (geOrchestra.js?ddf76ae26212cae88b44:2)
    at Ho (geOrchestra.js?ddf76ae26212cae88b44:2)
    at qo (geOrchestra.js?ddf76ae26212cae88b44:2)
    at Ks (geOrchestra.js?ddf76ae26212cae88b44:2)
```

 as soon as the **Configure templates** button is clicked in the context wizard.

![image](https://user-images.githubusercontent.com/1280027/111615909-8e510d80-87e1-11eb-9586-33b0bab19aa1.png)

**Comment by offtherailz** [comment]
This PR on MapStore (that will be backported) solves the issue https://github.com/geosolutions-it/MapStore2/pull/6677

**Comment by sigrmed** [comment]
It will be  backported on v1.2x ? Thank you @offtherailz  to inform me when the 1.2.x docker image will be updated

**Comment by sigrmed** [comment]
sigrmed = cat morales ;)

**Comment by tdipisa** [comment]
@catmorales @sigrmed the fix has been backported to the stable branch 1.2.x. Please, check it and let us know if we can close the issue. Thank you so much.

**Comment by sigrmed** [comment]
@tdipisa
I just redeployed mapstore to the v.1..2.x tag and this problem has been fixed. Thank you.
Catherine

**Comment by Gaetanbrl** [comment]
Hi, 
I reproduce this issue today with extension template v2023.01.02 on mapstore-georchestra 2022.x

**Comment by Gaetanbrl** [comment]
What can produce this error with custom plugin @offtherailz ?

**Comment by tdipisa** [comment]
@Gaetanbrl you should use the MS Extension version corresponding to the MS one used in geOrchestra otherwise you may experience some compatibility issues.

**Comment by Gaetanbrl** [comment]
@landryb https://github.com/geosolutions-it/MapStoreExtension#compatibility

... so i guess cadastrapp base on mapstoreExtension 2022.x is by definition not compatible until proved (test) otherwise.

**Comment by landryb** [comment]
> @landryb https://github.com/geosolutions-it/MapStoreExtension#compatibility
> 
> ... so i guess cadastrapp base on mapstoreExtension 2022.x is by definition not compatible until proved (test) otherwise.

apparently it 'works' but some features are broken (georchestra/mapstore2-cadastrapp#182)

havent tested yet either..

**Comment by Gaetanbrl** [comment]
> @Gaetanbrl you should use the MS Extension version corresponding to the MS one used in geOrchestra otherwise you may experience some compatibility issues.

My issue is due to :

https://github.com/geosolutions-it/MapStoreExtension/issues/59#issuecomment-1638332597
